### ISSUE TITLE
Great idea!  Can we get it to work with the Right Links WE extension?

### ISSUE THREAD

**Issue by Gitoffthelawn** [emvaized/circle-mouse-gestures#1]
Hi Max!

Congrats on releasing your new Circle Mouse Gestures web extension!

I just gave your project it's first star on GitHub! :)

I noticed it on AMO the other day, and I'm looking forward to trying it very soon.

It looks like a fantastic solution with a beautiful implementation.

I see you are working on it right now, so I thought I would mention my use case:  I would like to use it along with the Right Links WE extension (see https://github.com/Infocatcher/Right_Links_WE).  Alternatively, I suppose, it could replace Right Links, but that's a very solid and amazing extension.  No matter what, I would like to continue to right-click to open links in new tabs.

I haven't had sufficient time to think about exactly how I would like it to work, but I'm thinking either:

**_Model A_**
1. Right-clicking on a link will allow Right Links (or perhaps CMG) to open the the link in a new tab.
2. Long-right-clicking on a link will bring up the Firefox context menu.
3. Right-clicking on any HTML element that is not a link will bring up CMG.
4. Long-right-clicking on any HTML element that is not a link will bring up the Firefox context menu.
5. Long-left-clicking will have no special functionality (unless defined in Right Links).

**_Model B_**
1. Right-clicking on a link will allow Right Links (or perhaps CMG) to open the the link in a new tab.
2. Long-right-clicking on a link will bring up the Firefox context menu.
3. Right-clicking on any HTML element that is not a link will bring up the Firefox context menu.
4. Long-right-clicking on any HTML element that is not a link will bring up CMG.
5. Long-left-clicking will bring up CMG.

There are obviously other possibilities as well, but these are the top two models I'm thinking of right now.

What do you think?  Is either of these already possible with the current implementation of CMG?

Thanks, and congrats on your new extension!

**Comment by emvaized** [comment]
Hello @Gitoffthelawn!
Thanks for your review.

CMG in current implementation fully relies on opening the menu via the right mouse button press + selecting action on release, and left mouse button is reserved for a rocker action to open regular context menu (left click + right click). 
This pattern most likely will not change in the near future due to some limitations I faced during development (such as differences in how regular context menu is getting open on Windows and Linux/Mac OS).

I also don't see much of sense in listening for a long mouse click action, since it most likely will interfere with overall concept of visual menu - for example, some action may get called while you were just thinking of which action to choose, with right mouse button held down to keep the menu shown.

So if you really rely on long mouse click action in your workflow, the only compatibilty solution I could think of for now would be to add an option in settings, which will describe what CMG should do if no segments are enabled for the specific menu (for example links menu). It may contain 2 options - fallback to regular menu (current behavior), or do nothing (which will let you assign any actions for links in "Right Links WE"). I guess this scenario would be the most close to what you described as Model A.

Let me know what do you think

**Comment by Gitoffthelawn** [comment]
Hi Max!

You're welcome!

I need to think about this a bit more.  Overall, long-clicks are not as important to me as being able to right-click on a link to open it in a new tab.  I probably do that hundreds of times each day that I'm using a computer.  From what you are describing, I'm not sure that is currently possible (with or without Right Links WE).  Is it?

**Comment by emvaized** [comment]
Current verson 1.0.4 provides 2 options to quickly open link in new tab:
1) VIa the link menu (press down right button over link + swipe right + release). It also has another options for links ('copy url', 'open in background tab' etc), which can be configured in settings
2) Right click + left click to trigger rocker action (default action is 'Open in new tab' for links)

**Comment by Gitoffthelawn** [comment]
Thanks Max.

I'm trying to think of a way to use your tool and still have a short-right-click immediately open a link in a new tab.  "Right-swipe-release" and "right+left" probably will work well for people not accustomed to using right-click to open links in new tabs, but for those of use who have been using that method for years, the change might feel a bit slow and burdensome.

I'm thinking that perhaps Right Links WE could be used to open the links, and then using Right Links WE to call your extension on long-right-click or perhaps long-left-click.  Either that, or Right Links WE could just ignore those presses (it currently can catch them) and pass them on to you.

Alternatively, maybe your extension could have an option to pop-up on "right+left-click" as Right Links WE doesn't catch that at all.

I'm going to think about it a little, and maybe you'll have interest in doing the same.  I'm also hoping to actually play with your creation soon and see how the two extensions interact with each other as-is.

Regarding not catching all clicks, maybe take a look at Right Links WE for guidance.  It catches 99%+ of links I've encountered.

**Comment by Gitoffthelawn** [comment]
Thank you!  I will check it out!
