### ISSUE TITLE
Show browser menu on right click

### ISSUE THREAD

**Issue by ris58h** [emvaized/circle-mouse-gestures#15]
The extension works great but sometimes I need a native browser's menu. Could we have it on a right click? So right-and-hold-click will show a Circle menu.

**Comment by emvaized** [comment]
Please see the [FAQ](https://github.com/emvaized/circle-mouse-gestures#faq) > `How to open regular context menu?` section

Opening the regular menu by long press would be technically impossible, because the extension can not manually open the regular context menu whenever we want – it can only prevent the regular menu from opening, or allow it.
