### ISSUE TITLE
Can't reach some menu sections when menu is activated near a screen edge

### ISSUE THREAD

**Issue by ris58h** [emvaized/circle-mouse-gestures#16]
https://user-images.githubusercontent.com/511242/193536234-60d00abd-0f9c-41a2-a13f-0a1ce029589f.mov

**Comment by emvaized** [comment]
There's basically nothing we can do about it, as the screen edge is a natural boundary for a cursor, preventing it from moving farther. Every mouse gestures extension is affected by this, because usually you can't move the cursor out of the screen edge to finish the gesture. 

Circle Mouse Gestures tries to improve on this problem by shifting the menu when it goes off-screen (with few `Circle position` options in settings), and by providing an option to select highlighted action if cursor goes off-screen (`When cursor leaves window` option, defaults to `Hide menu`). 

I can not think of any better solution than this.
