### ISSUE TITLE
I would love to import or export my settings to another browser/PC

### ISSUE THREAD

**Issue by katastrophe92** [emvaized/circle-mouse-gestures#19]
First of all thank you for this amazing repository, I really LOVE IT!!!

I investe a good hour to set it up on LibreWolf how I want and it looks and feels amazing. Now I want to give Brave a try and without this  extension I can not use a Browser 👍 🥇 . But I'm not sure if I want to do it again ☹. Wit the import/export feature this extension is the Best. 

Thank you developer

**Comment by emvaized** [comment]
Hi there! Thanks a lot for your kind words. 
There is already a [feature request](https://github.com/emvaized/circle-mouse-gestures/issues/9) about import/export of settings, please discuss it there instead of opening new request, if it doesn't add something new to the topic. 

Despite this feature has been requested several times before, I don't actively develop this extension anymore, at least not at this life period. I may implement it once in the future, when I'll have time and motivation to do so, but no point for you for wait for it as it's not likely to happen today, tomorrow, or even this month.

**Comment by katastrophe92** [comment]
@emvaized I understand and wish you all the best and hope you will develop this amazing extension in the feature. No other extension like this is so complex and has everything you need

**Comment by emvaized** [comment]
Thanks, I've put a lot of time and effort in this extension back in the day, and it's always great to see someone really appreciate it
