### ISSUE TITLE
Add a "drag" option to Circle Mouse Gestures

### ISSUE THREAD

**Issue by sbstn87** [emvaized/circle-mouse-gestures#20]
Hi,

could you perhaps add an option to the extension, that allows for dragging, instead of holding the mouse button?

What I mean is something like this extension does:

https://addons.mozilla.org/en-US/firefox/addon/glitterdrag-pro/

This one allows for actions depending on dragging selected element. Implementing something like that would be awesome, as your extensions offers much more functionality in a very user friendly UI.

**Comment by emvaized** [comment]
Hi @sbstn87 Implementing such feature will probably require a complete rewrite of some parts of this extension — as CMG was initially designed for mouse gestures, and it remains it's main purpose and concept. And I don't really like such drag'n'drop type of interaction — but if I did, I would've rather preferred to create a new extension for this purpose instead of bringing it all to CMG.

If you really want drag'n'drop functionality, I'd recommend to better use the other extension you mentioned, and ask it's author to improve on it's functionality and UI instead.

**Comment by sbstn87** [comment]
Of course, that makes sense. Thank you for the reply.
