### ISSUE TITLE
Feature Request - Unique "Open menu on" or the addition of modifier keys.

### ISSUE THREAD

**Issue by sindacrof** [emvaized/circle-mouse-gestures#28]
If possible, it would be great to add an optional modifier key requirement for the different menu types. For example, regardless of what my mouse is hovering over, it will always go the regular menu, unless i am pressing a modifier key, at which point it would open the respective menu (e.g., link menu / image menu). Another option would be to allow different "Open menu on" based on the menu type. Just allowing the regular menu on right click, and the other menus on long left click would be perfect as well.

I may just be missing something in the settings, but it can be very frustrating when trying to navigate  around in the browser,  and don't' realize your are hovering over a picture or link or something, then you accidentally download an image. It gets especially bad on pages like Amazon where so much of the screen is images or links.

I believe you can get around this by inactivating the menus, but that makes them unusable for the times you actually do want to use them. 

Anyways, thank you for this extension, and my apologies if I am just clearly missing something.

I am using this extension on Opera GX

**Comment by emvaized** [comment]
Thanks for your suggestion! I'm glad you like this extension. 

I agree with you that this behavior sometimes creates a problem, when user is not aware that mouse cursor was actually over an image or a link. Back in the day I had an idea to cover it by adding a "combine" mode to the extension, which, when enabled, would add "special" menus as an additional outer levels to the main one instead of replacing it – but this idea turned out to mess up muscle memory. 

I think that it shouldn't be hard to add an option which will open "specific" menus only when one of the modifier keys are pressed. However, I'm worried that it would also neglect the main idea of working with gestures and performing actions using only the mouse, without touching the keyboard.

**Comment by emvaized** [comment]
New version 1.4.5 will include a new option "Require modifier key for non-regular menus", which when enabled will require any modifier key (Alt, Shift, Meta, Ctrl) to be pressed in order to show the non-regular menu (for images, links etc).

**Comment by sindacrof** [comment]
Ohh sweet, this will be a great feature and the option to enable/disable it
is a great compromise. I'll probably rebind a mouse key as the modifier
key, but in the future it might be worth allowing you to bind it to mouse
button 3/4, so we don't have to rebind the mouse keys.

Thanks for the update!

**Comment by emvaized** [comment]
> in the future it might be worth allowing you to bind it to mouse

It would be great to have this feature, but it seems not so easy to implement in a browser extension given its limitations. 

With few mouses I tested, it was not possible to catch back/forward buttons in the code, because when you press them the browser receives "back" or "forward" commands immediately, and the page itself doesn't receive any "back button was pressed" event, which can be listened to in the code and reassigned. Maybe it is designed this way in order to prevent malicious websites from hijacking back/forward mouse buttons...
